### ISSUE TITLE
Request for help: Is it necessary to increase the Java version of `KLS` to Java 21?

### ISSUE THREAD

**Issue by Krysztal112233** [lego-eden/fabricmod-scala-template#1]
Hello! I'm the maintainer of `krysztal-language-scala`, very glad you are using `KLS` as a temporary replacement for `FLS`!

It's been a while since I've been involved in mod development, and I've noticed that the Java version of Minecraft now requires Java 21. I'm not quite sure if `KLS`, which is made as a dependency library, needs to be similarly up-targeted to Java 21, so could you please test this for me?

I'm very sorry to bother you! I'm a bit busy with work and I can't devote myself to mod development for a while, so I'd like to ask you for a favor.

**Comment by lego-eden** [comment]
I have now tried to build the skeleton for minecraft 1.21 and I am happy to say that it works so far without problem. One curious detail is that the compatibility mode is set to Java 17 when running `gradlew runClient` even after updating.
